site_name: Documentation
site_url: https://sitename.example
watch:
  - includes
theme:
  name: material
  font:
  #    text: Inter
  #    text: Montserrat
  #    text: Lato
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Light mode
      primary: blue
#      accent: deep orange
      accent: blue
  #    code: Red Hat Mono
  features:
    - navigation.tabs  # THIS enables top nav bar (as tabs)
    - content.tooltips
markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_themed: false
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false

#nav:
#  - Home: index.md
#  - Docs: docs.md
#  - About: about.md
#  - Blog: blog.md
